name: Push File Workflow

on: 
  push:
    branches:
      - main

jobs:
  create_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run pytest and create file
        run: |
          pytest >> log_pytest.txt
          ls -a

      - name: Configure git
        run: |
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"

      - name: Commit and push
        run: |
          git add .
          git commit -m "random file from action" || echo "No changes to commit"
          git push
